INSERT INTO CALENDAR (ID, CALENDAR_IDENTIFIER, CALENDAR_VALUE)VALUES (1, 'custom', 'Calendario personale');
INSERT INTO CALENDAR (ID, CALENDAR_IDENTIFIER, CALENDAR_VALUE) VALUES (2, 'academic', 'Calendario accademico');
INSERT INTO CALENDAR (ID, CALENDAR_IDENTIFIER, CALENDAR_VALUE) VALUES (3, 'exams', 'Calendario esami');

INSERT INTO EVENT_TYPE (ID, EVENT_TYPE_IDENTIFIER, EVENT_TYPE_VALUE) VALUES (1, 'custom', 'Evento personale');
INSERT INTO EVENT_TYPE (ID, EVENT_TYPE_IDENTIFIER, EVENT_TYPE_VALUE) VALUES (2, 'lecture', 'Lezione');
INSERT INTO EVENT_TYPE (ID, EVENT_TYPE_IDENTIFIER, EVENT_TYPE_VALUE) VALUES (3, 'exam', 'Esame');
INSERT INTO EVENT_TYPE (ID, EVENT_TYPE_IDENTIFIER, EVENT_TYPE_VALUE) VALUES (4, 'news', 'News');
INSERT INTO EVENT_TYPE (ID, EVENT_TYPE_IDENTIFIER, EVENT_TYPE_VALUE) VALUES (5, 'administrative', 'Scadenza');

-- INSERT INTO STUDENT (id) VALUES (1);
-- INSERT INTO STUDENT (id) VALUES (2);
-- INSERT INTO STUDENT (id) VALUES (3);
-- INSERT INTO STUDENT (id) VALUES (4);
-- INSERT INTO STUDENT (id) VALUES (5);
-- INSERT INTO STUDENT (id) VALUES (6);
-- INSERT INTO STUDENT (id) VALUES (7);

